FROM mcr.microsoft.com/dotnet/core/runtime:3.1-buster-slim AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster AS build
WORKDIR /src
COPY ["LSSD.Registration.Notifier/LSSD.Registration.Notifier.csproj", "LSSD.Registration.Notifier/"]
COPY ["LSSD.Registration.FormGenerators/LSSD.Registration.FormGenerators.csproj", "LSSD.Registration.FormGenerators/"]
COPY ["LSSD.Registration.Model/LSSD.Registration.Model.csproj", "LSSD.Registration.Model/"]
COPY ["LSSD.Registration.Data/LSSD.Registration.Data.csproj", "LSSD.Registration.Data/"]
COPY ["LSSD.Registration.NotificationHandlers.EmailNotificationHandler/LSSD.Registration.NotificationHandlers.EmailNotificationHandler.csproj", "LSSD.Registration.NotificationHandlers.EmailNotificationHandler/"]
RUN dotnet restore "LSSD.Registration.Notifier/LSSD.Registration.ENotifiermailRunner.csproj"
COPY . .
WORKDIR "/src/LSSD.Registration.Notifier"
RUN dotnet build "LSSD.Registration.Notifier.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "LSSD.Registration.Notifier.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "LSSD.Registration.Notifier.dll"]